# -*- coding: utf-8 -*-
"""prediccion con moedelo entrenamiento h5 CIFAR10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AoE1IfKDk_SACxwS-1dkKGf7_BUvCxqH
"""

import tensorflow as  tf
import numpy as np
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing import image
import matplotlib.pyplot as plt

#cargar el modelo h5
from tensorflow.keras.models import load_model
model = load_model('/content/mejor_modelo_cifar10.h5')

class_name = ["airplane","automobile","bird","cat","deer","dog","frog","horse","ship","truck","human"]

#cargar la imagen
img = image.load_img('/content/imagesModelo2.jpg',target_size=(32,32))
#prediccion con la imagen
img_array = image.img_to_array(img)
#normalizacion
img_array = img_array.astype("float32") / 255.0
#agregar  la dimension del bathc(1,32,32,3)
img_array = np.expand_dims(img_array, axis=0)

#hacer prediccion
predictions = model.predict(img_array)
predictions
#quedarme con la que tenga mayor puntuacion
predicted_class = np.argmax(predictions)
# predicted_class
confidence = np.max(predictions)

print("La imagen pertenece a la clase:", class_name[predicted_class])
plt.imshow(img)
plt.title(f"Clase: {class_name[predicted_class]}")
plt.axis("off")
plt.show()

#ahora del rostro, identifica su estado de animo

# This is placeholder code. You would replace 'path/to/emotion_model.h5' with your actual model.
# from tensorflow.keras.models import load_model
# emotion_model = load_model('path/to/emotion_model.h5')

# Example of how you might load and preprocess a face image for emotion recognition
#This would typically involve a face detection library (like OpenCV or a dedicated face detection model)
import cv2
from tensorflow.keras.preprocessing import image
import numpy as np

# Define target_model_input_size for the emotion model (e.g., 48x48 pixels is common)
# IMPORTANT: This is currently set to 32 to match the CIFAR-10 model's input.
# For a true emotion model, this might be 48 or another size as per the model's requirements.
target_model_input_size = 32

# Assuming 'face_image_path' is the path to your image with a face
# face_img = image.load_img('/content/imagesModelo.jpg', target_size=(target_model_input_size, target_model_input_size))
# face_img_array = image.img_to_array(face_img)
# face_img_array = np.expand_dims(face_img_array, axis=0)
# face_img_array = face_img_array.astype('float32') / 255.0

# If you had an emotion model loaded, you would then predict:
# Note: 'model' currently refers to the CIFAR-10 model, not an emotion recognition model.
# You would need to load an appropriate emotion model (e.g., emotion_model = load_model('path/to/emotion_model.h5'))
emotion_predictions = model.predict(img_array)
predicted_emotion_class = np.argmax(emotion_predictions)
emotion_labels = ['angry', 'disgust', 'fear', 'happy', 'sad', 'surprise', 'neutral','crazy'] # Example labels
print(f"Predicted Emotion: {emotion_labels[predicted_emotion_class]}")