# -*- coding: utf-8 -*-
"""análisis de sentimientos modelo guardado.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EbyLKnhjZkaXhmbUzxuHgKYuJ9UOTV6y
"""

import pandas as pd
import joblib

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

from imblearn.over_sampling import SMOTE

from text_utils import limpiar_texto

# =============================
# Cargar dataset
# =============================

df = pd.read_csv("amazon_alexa.tsv", sep="\t")

df = df[["verified_reviews", "feedback"]]

df = df.dropna()

# =============================
# Limpiar texto
# =============================

df["clean_review"] = df["verified_reviews"].apply(limpiar_texto)

X = df["clean_review"]
y = df["feedback"]

# =============================
# Train / Test split
# =============================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=1
)

# =============================
# Vectorización
# =============================

vectorizer = CountVectorizer()

X_train_vect = vectorizer.fit_transform(X_train)
X_test_vect = vectorizer.transform(X_test)

# =============================
# Balanceo con SMOTE
# =============================

smote = SMOTE(random_state=42)

X_train_smote, y_train_smote = smote.fit_resample(
    X_train_vect,
    y_train
)

# =============================
# Modelo
# =============================

model = MultinomialNB()

model.fit(X_train_smote, y_train_smote)

# =============================
# Evaluación
# =============================

y_pred = model.predict(X_test_vect)

accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

print("\nResultados del modelo\n")

print("Accuracy :", accuracy)
print("Precision:", precision)
print("Recall   :", recall)
print("F1 score :", f1)

# =============================
# Guardar modelo + vectorizador
# =============================

modelo_completo = {
    "vectorizer": vectorizer,
    "model": model
}

joblib.dump(modelo_completo, "sentiment_model.joblib")

print("\nModelo guardado como sentiment_model.joblib")